name: surf 
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - alabaster=0.7.12=pyhd3eb1b0_0
  - apscheduler=3.9.0=py37h06a4308_0
  - asn1crypto=1.3.0=py37_1
  - astroid=2.3.3=py37_0
  - attrs=19.3.0=py_0
  - autopep8=1.4.4=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py37_0
  - beautifulsoup4=4.11.1=py37h06a4308_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - blinker=1.4=py37h06a4308_0
  - boost=1.68.0=py37h8619c78_1001
  - boost-cpp=1.68.0=h11c811c_1000
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.16.1=h7b6447c_0
  - ca-certificates=2024.12.31=h06a4308_0
  - cachetools=4.1.1=py_0
  - cairo=1.14.12=h8948797_3
  - catalogue=1.0.0=py37_1
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.13.2=py37h2e261b9_0
  - cftime=1.5.1.1=py37hce1f21e_0
  - chardet=3.0.4=py37h06a4308_1003
  - click=7.1.2=pyhd3eb1b0_0
  - cloudpickle=1.2.2=py_0
  - cryptography=2.8=py37h1ba5d50_0
  - cuda90=1.0=h6433d27_0
  - cuda91=1.0=h4c16780_0
  - cuda92=1.0=0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - curl=7.69.1=hbc83047_0
  - cycler=0.10.0=py37_0
  - cymem=2.0.2=py37hfd86e86_0
  - cython-blis=0.4.1=py37h7b6447c_1
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - deepsmiles=1.0.1=py_0
  - defusedxml=0.6.0=pyhd3eb1b0_0
  - docutils=0.16=py37_1
  - entrypoints=0.3=py37_0
  - et_xmlfile=1.1.0=py37h06a4308_0
  - expat=2.2.6=he6710b0_0
  - firefox=70.0.1=he1b5a44_0
  - flask=1.1.4=pyhd3eb1b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - future=0.18.3=py37h06a4308_0
  - gemmi=0.4.3=py37h5f9c2e6_1
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=hb3b607b_0
  - gmpy2=2.1.2=py37heeb90bb_0
  - google-auth=1.21.2=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.31.0=py37hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.8=py37_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.5.0=py37_0
  - inflect=4.1.0=py37_1
  - intel-openmp=2019.4=243
  - intermol=0.1=pyhd8ed1ab_0
  - ipykernel=5.1.4=py37h39e3cac_0
  - ipython=7.12.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.5.1=py_1
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=pyhd3eb1b0_0
  - jaraco.itertools=5.0.0=py_0
  - jedi=0.16.0=py37_1
  - jeepney=0.4.2=py_0
  - jinja2=2.11.1=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=habf39ab_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsoncpp=1.9.4=hff7bd54_2
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py37h06a4308_8
  - jupyter_client=5.3.4=py37_0
  - jupyter_console=6.1.0=pyhd3eb1b0_0
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=2.3.1=pyhd3eb1b0_0
  - jupyterlab_server=1.2.0=py_0
  - keyring=21.1.0=py37_0
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.17.1=h173b8e3_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lazy-object-proxy=1.4.3=py37h27cfd23_2
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.69.1=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libnetcdf=4.7.3=hb80b6cc_0
  - libogg=1.3.5=h27cfd23_1
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.11.2=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h7f8727e_2
  - libvorbis=1.3.7=h7b6447c_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - lz4-c=1.8.1.2=h14c3975_0
  - markdown=3.2.2=py37_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib=3.1.1=py37h5429711_0
  - matplotlib-base=3.2.1=py37hef1b27d_0
  - mccabe=0.6.1=py37h06a4308_2
  - memory_profiler=0.55.0=py_0
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - molvs=0.1.1=py_0
  - monty=2023.11.3=pyhd8ed1ab_0
  - more-itertools=8.2.0=py_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py37h06a4308_0
  - murmurhash=1.0.2=py37he6710b0_0
  - nbconvert=5.6.1=py37_1
  - nbformat=5.0.4=py_0
  - ncurses=6.1=he6710b0_1
  - netcdf4=1.5.3=py37hbf33ddf_0
  - networkx=2.6.3=pyhd3eb1b0_0
  - ninja=1.9.0=py37hfd86e86_0
  - nltk=3.4.5=py37_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=5.7.4=py37_0
  - numpydoc=0.9.2=py_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=pyhd3eb1b0_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1w=h7f8727e_0
  - palettable=3.3.0=pyhd3eb1b0_0
  - pandas=1.0.0=py37h0573a6f_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.6.0=py_0
  - patsy=0.5.1=py37_0
  - pcre=8.43=he6710b0_0
  - pep8=1.7.1=py37h06a4308_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - pixman=0.38.0=h7b6447c_0
  - plotly=5.9.0=py37h06a4308_0
  - preshed=3.0.2=py37he6710b0_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - protobuf=3.11.2=py37he6710b0_0
  - psutil=5.6.7=py37h7b6447c_0
  - ptyprocess=0.6.0=pyhd3eb1b0_2
  - py-boost=1.67.0=py37h04863e7_4
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pycairo=1.18.0=py37h2a1e443_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.19=py_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.5.2=py_0
  - pyjwt=1.7.1=py37_0
  - pylint=2.4.4=py37_0
  - pymatgen=2020.4.29=py37h99015e2_0
  - pyopenssl=19.1.0=pyhd3eb1b0_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.15.7=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.4.0=cuda101py37h02f0884_0
  - pytz=2019.3=py_0
  - pyyaml=6.0=py37h7f8727e_1
  - pyzmq=18.1.1=py37he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtawesome=0.6.1=py_0
  - qtconsole=4.6.0=py_1
  - qtpy=1.9.0=pyhd3eb1b0_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_1
  - requests-oauthlib=1.3.0=py_0
  - rope=0.16.0=py_0
  - rsa=4.6=py_0
  - ruamel.yaml=0.16.12=py37h7b6447c_1
  - ruamel.yaml.clib=0.2.6=py37h7f8727e_0
  - scikit-learn=0.21.3=py37hd81dba3_0
  - scipy=1.3.1=py37h7c811a0_0
  - seaborn=0.9.0=pyh91ea838_1
  - secretstorage=3.1.2=py37_1
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=45.1.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.14.0=py37h06a4308_0
  - snowballstemmer=2.0.0=pyhd3eb1b0_0
  - soupsieve=2.3.2.post1=py37h06a4308_0
  - spglib=1.16.0=py37h161383b_4
  - sphinx=2.3.1=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - spyder=3.3.6=py37_0
  - spyder-kernels=0.5.2=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - srsly=1.0.0=py37he1b5a44_0
  - statsmodels=0.11.0=py37h7b6447c_0
  - sympy=1.10.1=py37h06a4308_0
  - tabulate=0.8.10=py37h06a4308_0
  - tbb=2021.5.0=hd09550d_0
  - tenacity=8.0.1=py37h06a4308_1
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorboardx=2.0=py_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - tk=8.6.8=hbc83047_0
  - torchtext=0.5.0=py_1
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py37h06a4308_0
  - tzlocal=2.1=py37h06a4308_1
  - ujson=3.2.0=py37he6710b0_0
  - urllib3=1.25.8=py37_0
  - vtk=8.2.0=py37haa4764d_200
  - wasabi=0.6.0=py_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.34.2=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - wurlitzer=2.0.0=py37_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.1=he6710b0_3
  - zipp=2.1.0=py_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.3.7=h0b5b093_0
  - pip:
      - absl-py==2.1.0
      - ase==3.22.1
      - astunparse==1.6.3
      - flatbuffers==24.12.23
      - gast==0.4.0
      - google-pasta==0.2.0
      - h5py==3.8.0
      - keras==2.11.0
      - lammps-interface==0.2.2
      - libclang==18.1.1
      - llvmlite==0.39.1
      - numba==0.56.4
      - numpy==1.21.6
      - opt-einsum==3.3.0
      - packaging==24.0
      - parmed==4.0.0
      - python-version==0.0.2
      - rdkit==2023.3.2
      - shap==0.42.1
      - slicer==0.0.7
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - typing-extensions==4.7.1
prefix: /home/your_dir/miniconda3/envs/surf # path to your conda environment 
